### ISSUE TITLE
[lab2] "code" command not found on mac os

### ISSUE THREAD

**Issue by tingsu** [ecnu-sa-labs/ecnu-sa-labs#3]
I ran the `code` comand to open the vscode, got the error ``zsh: command not found: code`` according to the instruction below.

<img width="1031" alt="image" src="https://github.com/ecnu-sa-labs/ecnu-sa-labs/assets/3156978/c0928095-c278-475c-8f7d-95f80d81cbd9">

**Comment by hallo-mars** [comment]
The `code <lab2 directory>` requires the `code` command from VS Code to be added to the system PATH. If not configured during installation, an error will occur. The lab2 manual indeed did not mention this point :(

Using the `code` command to open the lab2 directory is optional. One can also directly open the lab2 folder within VS Code. And, with system PATH setup varying across platforms like Windows, MacOS, and Linux, I've chosen to omit that step as it's non-essential for completing the lab2. Commit link: https://github.com/ecnu-sa-labs/ecnu-sa-labs/commit/165463e7b680c4c8c51b61de045cf85cd556cf38.
